Implement backend endpoint for search by instructor
ucsb-cs156-s23/proj-courses-s23-7pm-3 pull request #18
Opened 2023-05-27 10:25 UTC by wq12li

In this PR, I've added backend support for searching courses by instructor and a quarter range. For the time being, this implementation is relatively simple and does not consider the difference between lectures and sections.

My implementation imitates that of the CourseOverTimeController.java file, and is mostly the same.

2023-05-27 18:31 UTC, khtran1 approved these changes, later dismissed
LGTM

2023-05-28 21:29 UTC, pconrad requested changes
Looks good... I'll be testing on the staff qa site before giving a final approval.

I would like you to add the `@ApiParam` annotation to the parameters to the new API endpoints though.

2023-05-28 21:29 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/courses/controllers/CourseOverTimeInstructorController.java
> +        @RequestParam String instructor
See my feedback on PR #19 here: 
https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-3/pull/19#discussion_r1208653470

I think adding similar `@ApiParam` annotations will make this easier for future programmers to work with.

2023-05-28 23:23 UTC, khtran1 approved these changes
LGTM

2023-05-30 20:03 UTC, pconrad approved these changes
LGTM!   Will test on staff-qa before merging.

2023-05-31 09:03 UTC, merged