yl - Create form component for instructor-based search
ucsb-cs156-s23/proj-courses-s23-7pm-3 pull request #42
Opened 2023-06-02 20:50 UTC by wq12li

In this PR, we add a frontend form component that allows for instructor-based search.

This component is modeled after the existing CourseOverTimeSearchForm component.

# Storybook (WIP)

# Screenshots (WIP)

Merging this PR closes #41.

2023-06-03 01:33 UTC, nagpalishaan submitted a review, later dismissed

2023-06-03 01:42 UTC, nagpalishaan commented
LGTM

2023-06-03 22:55 UTC, pconrad commented on frontend/src/main/components/BasicCourseSearch/CourseOverTimeInstructorSearchForm.js
> +  // Stryker restore OptionalChaining
Thank you!

2023-06-03 22:57 UTC, pconrad requested changes
A few small things... otherwise looks good.

2023-06-03 22:57 UTC, pconrad commented on frontend/src/main/components/BasicCourseSearch/CourseOverTimeInstructorSearchForm.js
> +
We need  this to match with the `// Stryker disable all`
```suggestion
// Stryker restore all
```

2023-06-03 22:57 UTC, pconrad commented on frontend/src/main/components/BasicCourseSearch/CourseOverTimeInstructorSearchForm.js
> +  // Stryker disable all : Stryker is testing by changing the padding to 0. But this is simply a visual optimization as it makes it look better
This should be removed, and if necessary, a test added for the CSS property.  Please see this web page for advice on how to do it:

https://ucsb-cs156.github.io/topics/stryker/stryker_html_attribute_surviving_mutants.html

2023-06-03 22:57 UTC, pconrad commented on frontend/src/stories/components/BasicCourseSearch/CourseOverTimeInstructorSearchForm.stories.js
> +//TODO: Backend API?
Please avoid comments like this in code that we are merging into main.

2023-06-04 00:54 UTC, wq12li commented
I've dealt with the stray comment in the stories file, and I've removed the `Stryker disable` on the padding. However, I'm not quite sure how to deal with adding the new `restore` line to the component.

If I add the restore immediately after the `getItem()` calls, mutations survive on the following three lines that call the `useState()` function. However, to kill those mutations, I think I need to mock local storage, which seems to be exactly the reason why someone added a `Stryker disable` into the file to begin with.

For the time being, I've moved the `restore` line to after the `useState()` calls to avoid this, but I'm not sure it's the right way to proceed.

Is there a good way that I can properly test the `useState()` calls, or is just skipping over them okay?

2023-06-05 20:09 UTC, pconrad requested changes
A few small items.

2023-06-05 20:09 UTC, pconrad commented on frontend/src/main/components/BasicCourseSearch/CourseOverTimeInstructorSearchForm.js
> +//import { allTheLevels } from "fixtures/levelsFixtures";
We should not have commented out imports in PRs to main.

Please remove this before making a PR.

And code reviewers, please point this out before we get to the staff review.  This will save a lot of time.

2023-06-05 20:09 UTC, pconrad commented on frontend/src/main/components/BasicCourseSearch/CourseOverTimeInstructorSearchForm.js
> +// import { useBackend  } from "main/utils/useBackend";
No commented out imports please

2023-06-05 20:09 UTC, pconrad commented on frontend/src/stories/components/BasicCourseSearch/CourseOverTimeInstructorSearchForm.stories.js
> +  submitText: "Create",
There is no submitText prop (i.e. parameter) for the `CourseOverTimeInstructorSearchForm` so this should not be here.  

The `Default.args` here are supposed to be the args passed into the component.  Your component takes only one prop, called `fetchJSON` so the line below is correct.

2023-06-05 21:02 UTC, pconrad approved these changes
LGTM!

2023-06-05 23:36 UTC, merged