kt - Add Files for Building Search dropdown menu
ucsb-cs156-s23/proj-courses-s23-7pm-3 pull request #45
Opened 2023-06-03 01:27 UTC by khtran1

# Description
This is the first of TBD PRs to implement the Building-based search feature.
## Added Files
-  `buildingFixtures.js`
    - Includes a list of (most, if not) all UCSB buildings where courses can be held to be used with a dropdown menu as well as examples to be used in testing.
    - Reminder that the list of buildings is not exhaustive and includes weird "buildings" like the track field. 
    - Manually compiled with a Python script connected to the MongoDB database
-  `SingleBuildingDropdown.js` and its tests and stories
    - The code to show a user-friendly dropdown menu allowing them to choose what to search for from a list of buildings on campus.

2023-06-04 01:28 UTC, wq12li approved these changes
Generally looks good.
Looking at this PR, I'm realizing that the fixtures files are a little inconsistent with whether or not they represent fixtures as key-value pairs in Objects, but I guess it's not something to deal with here.
Approved.

2023-06-04 01:41 UTC, wq12li requested changes
Wait, actually, upon closer inspection, there is a very tiny change that you could make:

I think all instances of "ssd" in SingleBuildingDropdown.test.js should be changed to "sbd"; "ssd" seems to be a remnant from the **S**ubject dropdown. The related level dropdown uses "sld," too, which I think implies that "sbd" would be the correct choice here.

2023-06-04 07:20 UTC, wq12li commented
I think you might've accidentally changed "ssd" to "sbd" in SingleSubjectDropdown instead of SingleBuildingDropdown.

2023-06-04 07:22 UTC, khtran1 commented
lol

2023-06-04 09:33 UTC, wq12li submitted a review, later dismissed
Looks good now.

2023-06-05 20:15 UTC, pconrad reviewed
In the description, you say:
```
Manually compiled with a Python script connected to the MongoDB database
```

Could you add that script to this PR in a top level directory called `scripts` along with a `README.md` file in that directory that explains how to use the script?

Be sure that you have embedded any passwords in the script (e.g. the MongoDB password or a URI containing the password) that you change those to placeholders before uploading the script.

We can make a future issue to replace this with some code that is embedded in the backend.

2023-06-05 20:17 UTC, pconrad requested changes
In the description, you say:
```
Manually compiled with a Python script connected to the MongoDB database
```

Could you add that script to this PR in a top level directory called `scripts` along with a `README.md` file in that directory that explains how to use the script?

Be sure that you have embedded any passwords in the script (e.g. the MongoDB password or a URI containing the password) that you change those to placeholders before uploading the script.

We can make a future issue to replace this with some code that is embedded in the backend.

2023-06-05 23:38 UTC, pconrad approved these changes
LGTM!

2023-06-08 04:40 UTC, merged